server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mydb}
      write-concern: ACKNOWLEDGED

  security:
    oauth2:
      client:
        registration:
          outlook:
            client-id: ${OUTLOOK_CLIENT_ID}
            client-secret: ${OUTLOOK_CLIENT_SECRET}
            scope: openid,profile,email,Mail.ReadWrite,Mail.Send,Contacts.ReadWrite,Calendars.ReadWrite,Files.ReadWrite.All,offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/callback/outlook
          gmail:
            client-id: ${GMAIL_CLIENT_ID}
            client-secret: ${GMAIL_CLIENT_SECRET}
            scope: openid,profile,email,
              https://www.googleapis.com/auth/gmail.readonly,
              https://www.googleapis.com/auth/gmail.send, 
              https://www.googleapis.com/auth/contacts,
              https://www.googleapis.com/auth/calendar,
              https://www.googleapis.com/auth/drive,
              https://www.googleapis.com/auth/gmail.insert,
              https://www.googleapis.com/auth/gmail.modify,
              https://www.googleapis.com/auth/gmail.labels
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/callback/gmail

logging:
  level:
    com.unwan.auth: DEBUG
    org.springframework.web: DEBUG
    com.microsoft.graph: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    com.mongodb: DEBUG